### PR TITLE
fix travis issues, rework data structure

### LINKED ISSUE #31: fix travis issues

### PR DESCRIPTION
**Pull request by khueyama**
Closes #31 

@sstrochak @awunderground this branch is passing travis-ci. You may want to make some more changes before merging to master, but for now I have done the following:

* Bumped version to 0.0.0.9001
* Added a (draft) NEWS file
* Reworked `get_urbn_map` and `get_urbn_labels` to fail gracefully and tweaked "territories_counties" argument for consistency across both
* Moved all data except `states`, `counties`, `statedata`, and `countydata` to `R/sysdata.rda`. The only data frames that appear in the namespace are those four now. Everything else can still be called by `get_urbn_map` and `get_urbn_labels` (and whatever else may end up in the `R/` directory. Check out `data-raw/generate_sysdata.R` to see how and what I'm saving to `R/sysdata.rda`.

If you can, please install from this branch and test it out. It's a fairly extensive reworking and you both know the ccdf and territories functionality much better than I do

### CODE REVIEW

**Comment by khueyama** [comment]
@awunderground I think working on this branch is fine for now. I made a couple additional changes to and for the new vignette:

- All data frames except `states`, `counties`, `statedata`, and `countydata` are in `R/sysdata.rda` and not available in the namespace. Updated the `label` section of the vignette to reflect that it can only be accessed via `get_urbn_labels` - we can always rework that if you all want, but that's the way it's set up now.
- Packages used in vignettes but not the package itself go under 'Suggests' of the DESCRIPTION file. So `tidyverse`, `urbnthemes`, and `scales` have been added there. Probably want to rethink the use of `urbnthemes` in the vignette for now - pretty sure this won't work for CRAN since it's only available via GitHub. 
- The `docs/` directory added to .Rbuildignore so that the package doesn't try to include that directory on installation
- `urbnthemes` added to the travis build

**Comment by awunderground** [comment]
@khueyama This is great. I'm so fortunate to work with someone who understands everything I don't. 

Hmm, I'm not sure if urbnthemes will ever be on CRAN. That's inconvenient.

**Comment by sstrochak** [comment]
I tested this out and everything is working on my end.

**Comment by awunderground** [comment]
@khueyama @sstrochak Are we waiting to merge this for a specific reason?

**Pull request merged**
